(cl:defpackage irobotcreate2-msg
  (:use )
  (:export
   "<BATTERY>"
   "BATTERY"
   "<BRUSHES>"
   "BRUSHES"
   "<BUMPER>"
   "BUMPER"
   "<BUTTONS>"
   "BUTTONS"
   "<DIAGNOSTIC>"
   "DIAGNOSTIC"
   "<DIGITLEDS>"
   "DIGITLEDS"
   "<IRCHARACTER>"
   "IRCHARACTER"
   "<LEDS>"
   "LEDS"
   "<NOTE>"
   "NOTE"
   "<PLAYSONG>"
   "PLAYSONG"
   "<ROOMBAIR>"
   "ROOMBAIR"
   "<ROOMBASWITCH>"
   "ROOMBASWITCH"
   "<SCHEDULELEDS>"
   "SCHEDULELEDS"
   "<SONG>"
   "SONG"
   "<WHEELDROP>"
   "WHEELDROP"
  ))

